# Generated by Django 3.0 on 2020-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlako_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='subject_identifier',
            field=models.CharField(max_length=50, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='subject_identifier',
            field=models.CharField(max_length=50, verbose_name='Subject Identifier'),
        ),
    ]
