from .constants import DOCTOR_OTHER, NURSE_OTHER
from edc_constants.constants import OTHER

CLINICIAN_TYPE = (
    ('Medical Officer', 'Medical Officer'),
    ('Specialist - Family Medicine', 'Specialist - Family Medicine'),
    ('Specialist - Internal Medicine', 'Specialist - Internal Medicine'),
    ('Specialist - General Surgeon', 'Specialist - General Surgeon'),
    ('Specialist - Ob/GYN (Gynecologist)',
     'Specialist - Ob/GYN (Gynecologist)'),
    ('Specialist - Oncologist', 'Specialist - Oncologist'),
    ('Specialist - Pathologist', 'Specialist - Pathologist'),
    ('Specialist - Hematologist', 'Specialist - Hematologist'),
    ('Specialist - Palliative care', 'Specialist - Palliative care'),
    (DOCTOR_OTHER, 'Doctor - Other type (specify)')
    ('Nurse - FNP', 'Nurse - FNP'),
    ('Nurse - Midwife', 'Nurse - Midwife'),
    ('Nurse - Community health', 'Nurse - Community health'),
    (NURSE_OTHER, 'Nurse - Other type (specify)'),
    ('Nurse - RN', 'Nurse - RN')
)

FACILITY = (
    ('Boatlaname HP', 'Boatlaname HP'),
    ('Bokaa PC', 'Bokaa PC'),
    ('Borakalalo PC', 'Borakalalo PC'),
    ('Boribamo PC', 'Boribamo PC'),
    ('Boswelakoko PC', 'Boswelakoko PC'),
    ('Ditshukudu HP', 'Ditshukudu HP'),
    ('Gakgatla HP', 'Gakgatla HP'),
    ('Gakuto HP', 'Gakuto HP'),
    ('Gamodubu HP', 'Gamodubu HP'),
    ('Hatsalatladi HP', 'Hatsalatladi HP'),
    ('Kgope HP', 'Kgope HP'),
    ('Kgosing PC', 'Kgosing PC'),
    ('Kopong PC', 'Kopong PC'),
    ('Kubung HP', 'Kubung HP'),
    ('Kumakwane HP', 'Kumakwane HP'),
    ('Kweneng HP', 'Kweneng HP'),
    ('Lekgwapheng HP', 'Lekgwapheng HP'),
    ('Lentsweletau PC', 'Lentsweletau PC'),
    ('Lephepe PC', 'Lephepe PC'),
    ('Lesilakgokong HP', 'Lesilakgokong HP'),
    ('Loologane PC', 'Loologane PC'),
    ('Magokotswane HP', 'Magokotswane HP'),
    ('Mahetlwe HP', 'Mahetlwe HP'),
    ('Medie HP', 'Medie HP'),
    ('Mmankgodi PC', 'Mmankgodi PC'),
    ('Mmanoko HP', 'Mmanoko HP'),
    ('Mmatseta HP', 'Mmatseta HP'),
    ('Mogonono HP', 'Mogonono HP'),
    ('Molepolole Community Clinic PC', 'Molepolole Community Clinic PC'),
    ('Phuthadikobo PC', 'Phuthadikobo PC'),
    ('Phuting HP', 'Phuting HP'),
    ('Rungwane HP', 'Rungwane HP'),
    ('Shadishadi HP', 'Shadishadi HP'),
    ('SLH', 'SLH - Scotting Livingstone Hospital'),
    ('Sojwe PC', 'Sojwe PC'),
    ('Thamaga PC', 'Thamaga PC'),
    ('TPH', 'TPH - Thamaga PH'),
    ('Marotse MS', 'Marotse MS'),
    ('Chaoke MS', 'Chaoke MS'),
    ('Dam 18 MS', 'Dam 18 MS'),
    ('Dikgathong MS', 'Dikgathong MS'),
    ('Dikhutsana MS', 'Dikhutsana MS'),
    ('Diphepe MS', 'Diphepe MS'),
    ('Gamatsela MS', 'Gamatsela MS'),
    ('Gamononyane MS', 'Gamononyane MS'),
    ('Hubasanoko MS', 'Hubasanoko MS'),
    ('Kaminakwe MS', 'Kaminakwe MS'),
    ('Kgapamadi MS', 'Kgapamadi MS'),
    ('Khuduyamajako MS', 'Khuduyamajako MS'),
    ('Kokonje MS', 'Kokonje MS'),
    ('Lekgatshwane MS', 'Lekgatshwane MS'),
    ('Maanege MS', 'Maanege MS'),
    ('Mapateng MS', 'Mapateng MS'),
    ('Mmakanke MS', 'Mmakanke MS'),
    ('Mmamarobole MS', 'Mmamarobole MS'),
    ('Mmamohiko MS', 'Mmamohiko MS'),
    ('Mmankgodi East MS', 'Mmankgodi East MS'),
    ('Mmaothate MS', 'Mmaothate MS'),
    ('Mmapaba MS', 'Mmapaba MS'),
    ('Mmasebele MS', 'Mmasebele MS'),
    ('Moamoge MS', 'Moamoge MS'),
    ('Moetlo MS', 'Moetlo MS'),
    ('Mophakane MS', 'Mophakane MS'),
    ('MoseKELE MS', 'MoseKELE MS'),
    ('Moselele 1 MS', 'Moselele 1 MS'),
    ('Moselele 2 MS', 'Moselele 2 MS'),
    ('Mosokotso MS', 'Mosokotso MS'),
    ('Motlabaki MS', 'Motlabaki MS'),
    ('Phiriyabokwetse MS', 'Phiriyabokwetse MS'),
    ('Ramagapu MS', 'Ramagapu MS'),
    ('Ramakgatlanyane MS', 'Ramakgatlanyane MS'),
    ('Ramankhung MS', 'Ramankhung MS'),
    ('Ramaphatle MS', 'Ramankhung MS'),
    ('Ramasenyane MS', 'Ramasenyane MS'),
    ('Rammidi MS', 'Rammidi MS'),
    ('Rasegwagwa MS', 'Rammidi MS'),
    ('Sasakwe MS', 'Sasakwe MS'),
    ('Sekhukhwane MS', 'Sekhukhwane MS'),
    ('Sepene MS', 'Sepene MS'),
    ('Shonono MS', 'Shonono MS'),
    ('Suping MS', 'Suping MS'),
    ('Scatter & Lamber PC (private)', 'Scatter & Lamber PC (private)'),
    ('Ikago PC', 'Ikago PC'),
    ('Molepopole Education Centre PC', 'Molepopole Education Centre PC'),
    ('Molepolole Prisons PC', 'Molepolole Prisons PC'),
    ('Princess Marina Hospital', 'Princess Marina Hospital'),
)

FACILITY_UNIT = (
    ('OPD', 'OPD'),
    ('A&E', 'A&E'),
    ('IDCC', 'IDCC'),
    ('Medicine ward', 'Medicine ward'),
    ('GYN ward', 'GYN ward'),
    ('Surgery ward', 'Surgery ward'),
    (OTHER, 'Other'),
)

DISTRICT = (
    ('Chobe', 'Chobe - Chobe'),
    ('Bobonong', 'Central - Bobonong'),
    ('Boteti', 'Central - Boteti'),
    ('Mahalapye', 'Central - Mahalapye'),
    ('Orapa', 'Central - Orapa'),
    ('Serowe/Palapye', 'Central - Serowe/Palapye'),
    ('Tutume', 'Central - Tutume'),
    ('CKGR', 'Ghanzi - CKGR'),
    ('Ghanzi', 'Ghanzi - Ghanzi'),
    ('Kgalagdi_North', 'Kgalagadi North'),
    ('Kgalagadi_South', 'Kgalagadi South'),
    ('Kgatleng', 'Kgatleng'),
    ('Kweneng_East', 'Kweneng - East'),
    ('Kweneng_West', 'Kweneng - West'),
    ('Delta', 'North West - Delta'),
    ('Ngamiland_North', 'North West - Ngamiland Nort'),
    ('Ngamiland_South', 'North East - Ngamiland South'),
    ('North_East', 'North East'),
    ('Barolong', 'Southern - Barolong'),
    ('Ngwaketse', 'Southern - Ngwaketse'),
    ('Ngwaketse_West', 'Southern - Ngwaketse West'),
)

KIN_RELATIONSHIP = (
    ('SPOUSE', 'Spouse'),
    ('CHILD', 'Child'),
    ('PARENT', 'Parent'),
    ('SIBLING', 'Sibling'),
    ('GRANDPARENTS', 'Grandparents'),
    ('GRANDCHILD', 'Grandchild'),
    (OTHER, 'Other')
    )
