from .constants import DOCTOR_OTHER, NURSE_OTHER
from edc_constants.constants import OTHER

CLINICIAN_TYPE = (
    ('med_officer', 'Medical Officer'),
    ('fam_medicine', 'Specialist - Family Medicine'),
    ('internal_medicine', 'Specialist - Internal Medicine'),
    ('general_surgeon', 'Specialist - General Surgeon'),
    ('ob_gyn', 'Specialist - Ob/GYN (Gynecologist)'),
    ('oncologist', 'Specialist - Oncologist'),
    ('pathologist', 'Specialist - Pathologist'),
    ('hematologist', 'Specialist - Hematologist'),
    ('palliative_care', 'Specialist - Palliative care'),
    (DOCTOR_OTHER, 'Doctor - Other type (specify)')
    ('FNP', 'Nurse - FNP'),
    ('midwife', 'Nurse - Midwife'),
    ('community_health', 'Nurse - Community health'),
    (NURSE_OTHER, 'Nurse - Other type (specify)'),
    ('RN', 'Nurse - RN')
)

FACILITY = (
    ('boatlaname_hp', 'Boatlaname HP'),
    ('bokaa_pc', 'Bokaa PC'),
    ('borakalalo_pc', 'Borakalalo PC'),
    ('boribamo_pc', 'Boribamo PC'),
    ('boswelakoko_pc', 'Boswelakoko PC'),
    ('ditshukudu_hp', 'Ditshukudu HP'),
    ('gakgatla_hp', 'Gakgatla HP'),
    ('gakuto_hp', 'Gakuto HP'),
    ('gamodubu_hp', 'Gamodubu HP'),
    ('hatsalatladi_hp', 'Hatsalatladi HP'),
    ('kgope_hp', 'Kgope HP'),
    ('kgosing_pc', 'Kgosing PC'),
    ('kopong_pc', 'Kopong PC'),
    ('kubung_hp', 'Kubung HP'),
    ('kumakwane_hp', 'Kumakwane HP'),
    ('kweneng_hp', 'Kweneng HP'),
    ('lekgwapheng_hp', 'Lekgwapheng HP'),
    ('lentsweletau_pc', 'Lentsweletau PC'),
    ('lephepe_pc', 'Lephepe PC'),
    ('lesilakgokong_hp', 'Lesilakgokong HP'),
    ('loologane_pc', 'Loologane PC'),
    ('magokotswane_hp', 'Magokotswane HP'),
    ('mahetlwe_hp', 'Mahetlwe HP'),
    ('medie_hp', 'Medie HP'),
    ('mmankgodi_pc', 'Mmankgodi PC'),
    ('mmanoko_hp', 'Mmanoko HP'),
    ('mmatseta_hp', 'Mmatseta HP'),
    ('mogonono_hp', 'Mogonono HP'),
    ('molepolole_comm_clinic_pc', 'Molepolole Community Clinic PC'),
    ('phuthadikobo_pc', 'Phuthadikobo PC'),
    ('phuting_hp', 'Phuting HP'),
    ('rungwane_hp', 'Rungwane HP'),
    ('shadishadi_hp', 'Shadishadi HP'),
    ('SLH', 'SLH - Scotting Livingstone Hospital'),
    ('sojwe_pc', 'Sojwe PC'),
    ('thamaga_pc', 'Thamaga PC'),
    ('TPH', 'TPH - Thamaga PH'),
    ('marotse_ms', 'Marotse MS'),
    ('chaoke_ms', 'Chaoke MS'),
    ('dam18_ms', 'Dam 18 MS'),
    ('dikgathong_ms', 'Dikgathong MS'),
    ('dikhutsana_ms', 'Dikhutsana MS'),
    ('diphepe_ms', 'Diphepe MS'),
    ('gamatsela_ms', 'Gamatsela MS'),
    ('gamononyane_ms', 'Gamononyane MS'),
    ('hubasanoko_ms', 'Hubasanoko MS'),
    ('kaminakwe_ms', 'Kaminakwe MS'),
    ('kgapamadi_ms', 'Kgapamadi MS'),
    ('khuduyamajako_ms', 'Khuduyamajako MS'),
    ('kokonje_ms', 'Kokonje MS'),
    ('lekgatshwane_ms', 'Lekgatshwane MS'),
    ('maanege_ms', 'Maanege MS'),
    ('mapateng_ms', 'Mapateng MS'),
    ('mmakanke_ms', 'Mmakanke MS'),
    ('mmamarobole_ms', 'Mmamarobole MS'),
    ('mmamohiko_ms', 'Mmamohiko MS'),
    ('mmankgodi_east_ms', 'Mmankgodi East MS'),
    ('mmaothate_ms', 'Mmaothate MS'),
    ('mmapaba_ms', 'Mmapaba MS'),
    ('mmasebele_ms', 'Mmasebele MS'),
    ('moamoge_ms', 'Moamoge MS'),
    ('moetlo_ms', 'Moetlo MS'),
    ('mophakane_ms', 'Mophakane MS'),
    ('mosekele_ms', 'MoseKELE MS'),
    ('moselele1_ms', 'Moselele 1 MS'),
    ('moselele2_ms', 'Moselele 2 MS'),
    ('mosokotso_ms', 'Mosokotso MS'),
    ('motlabaki_ms', 'Motlabaki MS'),
    ('phiriyabokwetse_ms', 'Phiriyabokwetse MS'),
    ('ramagapu_ms', 'Ramagapu MS'),
    ('ramakgatlanyane_ms', 'Ramakgatlanyane MS'),
    ('ramankhung_ms', 'Ramankhung MS'),
    ('ramaphatle_ms', 'Ramankhung MS'),
    ('ramasenyane_ms', 'Ramasenyane MS'),
    ('rammidi_ms', 'Rammidi MS'),
    ('rasegwagwa_ms', 'Rammidi MS'),
    ('sasakwe_ms', 'Sasakwe MS'),
    ('sekhukhwane_ms', 'Sekhukhwane MS'),
    ('sepene_ms', 'Sepene MS'),
    ('shonono_ms', 'Shonono MS'),
    ('suping_ms', 'Suping MS'),
    ('scatter&lamber_pc', 'Scatter & Lamber PC (private)'),
    ('ikago_pc', 'Ikago PC'),
    ('mec_pc', 'Molepopole Education Centre PC'),
    ('molepolole_prisons_pc', 'Molepolole Prisons PC'),
    ('princess_marina', 'Princess Marina Hospital'),
)

FACILITY_UNIT = (
    ('OPD', 'OPD'),
    ('A&E', 'A&E'),
    ('IDCC', 'IDCC'),
    ('medicine_ward', 'Medicine ward'),
    ('GYN_ward', 'GYN ward'),
    ('surgery_ward', 'Surgery ward'),
    (OTHER, 'Other'),
)

DISTRICT = (
    ('chobe', 'Chobe - Chobe'),
    ('bobonong', 'Central - Bobonong'),
    ('boteti', 'Central - Boteti'),
    ('mahalapye', 'Central - Mahalapye'),
    ('orapa', 'Central - Orapa'),
    ('serowe_palapye', 'Central - Serowe/Palapye'),
    ('tutume', 'Central - Tutume'),
    ('CKGR', 'ghanzi - CKGR'),
    ('ghanzi', 'ghanzi - Ghanzi'),
    ('kgalagdi_north', 'Kgalagadi North'),
    ('kgalagadi_south', 'Kgalagadi South'),
    ('kgatleng', 'Kgatleng'),
    ('kweneng_east', 'Kweneng - East'),
    ('kweneng_west', 'Kweneng - West'),
    ('delta', 'north West - Delta'),
    ('ngamiland_north', 'North West - Ngamiland Nort'),
    ('ngamiland_south', 'North East - Ngamiland South'),
    ('north_east', 'North East'),
    ('barolong', 'Southern - Barolong'),
    ('ngwaketse', 'Southern - Ngwaketse'),
    ('ngwaketse_west', 'Southern - Ngwaketse West'),
)

KIN_RELATIONSHIP = (
    ('spouse', 'Spouse'),
    ('child', 'Child'),
    ('parent', 'Parent'),
    ('sibling', 'Sibling'),
    ('grandparents', 'Grandparents'),
    ('grandchild', 'Grandchild'),
    (OTHER, 'Other')
)
